### ISSUE TITLE
The number of attempts is 1 more than "freeRetries" value

### ISSUE THREAD

**Issue by Tezaruz** [AdamPflug/express-brute#85] opened 2020-02-13 15:22 UTC
Readme says that

> freeRetries The number of retries the user has before they need to start waiting (default: 2)

but if you install freeRetries === 5, then the library gives you 6 queries and only after that the user starts to wait.

**Comment by TheAndroidGuy** [comment] 2020-02-13 16:17
Duplicate of #82

**Closed** 2020-02-14 19:43 UTC
